apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: spring-mysql
spec:
  selector:
    matchLabels:
      run: spring-mysql
  replicas: 1
  template:
    metadata:
      labels:
        run: spring-mysql 
    spec:
      containers:
      - name: spring-mysql 
        image: bingli7/spring-mysql:0823 
        ports:
        - containerPort: 8080
